### ISSUE TITLE
Plugin is not building in Alcatraz

### ISSUE THREAD

**Issue by guillaumealgis** [MakeZL/ZLCheckFilePlugin-Xcode#1]
This is due to the fact that Alcatraz is looking for a `xcodeproj` file with the exact same name as the plugin when building.

In this case, the plugin is named `ZLCheckFile` and the xcodeproj `ZLCheckFilePlugin.xcodeproj`.
So either rename the plugin with a PR on [alcatraz-packages](https://github.com/supermarin/alcatraz-packages), or rename the xcodeproj to `ZLCheckFile.xcodeproj`.

**Comment by Hs-Yeah** [comment]
+1

**Comment by caoer** [comment]
:+1:

**Comment by caoer** [comment]
created a PR for this issue: https://github.com/MakeZL/ZLCheckFilePlugin-Xcode/pull/2

**Comment by guillaumealgis** [comment]
We fixed the way we discover the xcodeproj file in Alcatraz (see https://github.com/alcatraz/Alcatraz/pull/471).

The plugin will install fine with the next release of Alcatraz.
